[#include "notificationCommonsText.ftl" ]
[@buildNotificationTitleText build buildSummary/][#t]
[#if buildSummary.successful]
 was SUCCESSFUL[#rt]
       [#if numFailures > 0]
 after ${numFailures} failures.[#rt]
       [/#if]
[#else]
 has FAILED[#rt]
    [#if numFailures > 0]
 (${numFailures} times).[#rt]
    [/#if]
[/#if]