[#-- @ftlvariable name="build" type="com.atlassian.bamboo.build.Buildable" --]
[#-- @ftlvariable name="buildSummary" type="com.atlassian.bamboo.resultsummary.BuildResultsSummary" --]
[#-- @ftlvariable name="triggerReasonDescription" type="java.lang.String" --]
[#-- @ftlvariable name="htmlUtils" type="com.atlassian.bamboo.util.HtmlUtils" --]
[#include "notificationCommons.ftl"]
[#import "notificationCommonsText.ftl" as nc ]
----------------------------------------------------------------------------
[#if buildSummary.successful]
[@nc.buildNotificationTitleText build buildSummary/] was successful[@showRestartCount buildSummary/].
[#else]
[@nc.buildNotificationTitleText build buildSummary/] failed[@showRestartCount buildSummary/].
[/#if]
----------------------------------------------------------------------------
[#assign testSummary = buildSummary.testResultsSummary /]
[#if buildSummary.successful]
    [#if triggerReasonDescription?has_content]
        ${triggerReasonDescription}[#lt]
    [/#if]
    [#if testSummary.totalTestCaseCount == 0]
        No tests executed.[#lt]
    [#else]
        ${testSummary.successfulTestCaseCount} tests in total.[#lt]
    [/#if]
[#else]
    [#if triggerReasonDescription?has_content]
        ${triggerReasonDescription}[#lt]
    [/#if]
    [@nc.displayBuildFailureMessage buildSummary /]
[/#if]

${baseUrl}/browse/${buildSummary.planResultKey}/

[#if buildSummary.commits?has_content]

--------------
Code Changes
--------------
[#list buildSummary.commits as commit]
[#if commit_index gte 3][#break][/#if]
[#assign guessedRevision = commit.guessChangeSetId()!("")]
${commit.author.fullName}[#if guessedRevision?has_content] (${guessedRevision})[/#if]:

${htmlUtils.addPrefixToLines(">", commit.comment)}

[/#list]
[/#if]

[#assign hasExistingFailedTests=testSummary.existingFailedTestCount gt 0 /]
[#assign hasNewlyFailingTests=testSummary.newFailedTestCaseCount gt 0 /]
[#assign hasFixedTests=testSummary.fixedTestCaseCount gt 0 /]
[#assign numTests=0 /]
[#assign maxTests=25 /]
[#if buildSummary.filteredTestResults?? && (hasExistingFailedTests || hasNewlyFailingTests || hasFixedTests)]
[#assign testResults = buildSummary.filteredTestResults /]

--------------
Tests
--------------
[#if hasExistingFailedTests ||  hasNewlyFailingTests]
[#assign failedTestTotal=testSummary.newFailedTestCaseCount + testSummary.existingFailedTestCount /]
Failed Tests (${failedTestTotal})
  [#list testResults.newFailedTests.values() as testResult]
    [#if numTests gte maxTests][#break][/#if]
[@displayTest testResult "(New)" /]
  [/#list]
  [#list testResults.existingFailedTests.values() as testResult]
    [#if numTests gte maxTests][#break][/#if]
[@displayTest testResult "(Existing)" /]
  [/#list]

[/#if]
[#if hasFixedTests && numTests lt maxTests]
Fixed Tests (${testSummary.fixedTestCaseCount})
   [#list testResults.fixedTests.values() as testResult]
    [#if numTests gte maxTests][#break][/#if]
[@displayTest testResult /]
   [/#list]

[/#if]
[/#if]
[#if shortErrorSummary.size() gt 0]

--------------
Error Summary
--------------
[#list shortErrorSummary as error]
   ${htmlUtils.getAsPreformattedText(error)}
[/#list]

[/#if]

--
This message is automatically generated by Atlassian Bamboo

[#macro displayTest testResult postfix='']
    [#assign numTests = numTests + 1 /]
   - ${testResult.testClassResult.shortName}: ${testResult.methodName} ${postfix}
[/#macro]