[#-- @ftlvariable name="build" type="com.atlassian.bamboo.build.Buildable" --]
[#-- @ftlvariable name="buildSummary" type="com.atlassian.bamboo.resultsummary.BuildResultsSummary" --]
[#include "notificationCommonsText.ftl" ]
[@buildNotificationTitleText build buildSummary/] [#t]
[#if buildSummary.successful]
was SUCCESSFUL[#t]
[#if buildSummary.testResultsSummary.successfulTestCaseCount > 0]
 (with ${buildSummary.testResultsSummary.successfulTestCaseCount} test[#if buildSummary.testResultsSummary.successfulTestCaseCount!=1]s[/#if])[#rt]
[/#if]
[#elseif buildSummary.failed]
has FAILED[#t]
[#if buildSummary.testResultsSummary.failedTestCaseCount > 0]
 (${buildSummary.testResultsSummary.failedTestCaseCount} test[#if buildSummary.testResultsSummary.failedTestCaseCount!=1]s[/#if] failed[#rt]
[#if buildSummary.testResultsSummary.existingFailedTestCount > 0]
, [#t]
[#if buildSummary.testResultsSummary.newFailedTestCaseCount > 0]
${buildSummary.testResultsSummary.newFailedTestCaseCount} [#t]
[#else]
no [#t]
[/#if]
failures were new[#t]
[/#if]
)[#t]
[/#if]
[#else]
was NOT BUILT[#t]
[/#if]
[#assign authors=buildSummary.uniqueAuthors /]
[#if authors?has_content]
  [#if authors.size() <= 3]
. Change made by [#t]
      [#assign first=true/]
      [#list authors as author]
            [#if !first]
                [#if author_has_next]
, [#t]
                [#else]
 and [#rt]
                [/#if]
            [#else]
                [#assign first=false]
            [/#if]
${author.fullName}[#t]
      [/#list]
.[#t]
   [#else]
. Change made by ${authors.size()} authors.[#t]
    [/#if]
[/#if]