-------------------------------------------------------------------------------
Error detected for ${error.buildName}[#if error.buildNumber?has_content && error.buildExists] > ${error.buildResultKey}[/#if].
-------------------------------------------------------------------------------

[#if error.context?has_content]
${error.context}
[/#if]

${baseUrl}/browse/${error.parentPlanKey}#buildPlanSummaryErrorLog

[#if error.numberOfOccurrences == 1]
Occurred:      ${error.lastOccurred?datetime}
[#else]
Occurrences:    ${error.numberOfOccurrences}
First Occurred: ${error.firstOccurred?datetime}
Last Occurred:  ${error.lastOccurred?datetime}
[/#if]
[#if error.agentIds?has_content]
Agent[#if error.agents.size() != 1]s[/#if]:         [#t]
    [#list error.agents as agent]
        ${agent.name?html}[#lt]
        [#if agent_has_next]
            ,[#lt]
        [/#if]
    [/#list]
[/#if]

[#if error.throwableDetails?has_content]
--------------
Exception Details
--------------

   [#if error.throwableDetails.name?has_content]
${error.throwableDetails.name?html}[#if error.throwableDetails.message?has_content]:[/#if]
   [/#if]
   [#if error.throwableDetails.message?has_content]
${error.throwableDetails.message?html}
   [/#if]

--------------
Stack Trace
--------------

[#if error.throwableDetails.stackTrace?has_content]
${error.throwableDetails.stackTrace?html}
[/#if]
[/#if]

--
This message is automatically generated by Atlassian Bamboo