[#if addedComment.user??]
${fn.getUserFullName(addedComment.user)} [#t]
[#elseif addedComment.userName??]
${addedComment.userName} [#t]
[#else]
Anonymous User [#t]
[/#if]
commented on [#t]
${buildSummary.planResultKey}:[#lt]
${addedComment.content}[#lt]
${baseUrl}/browse/${buildSummary.planResultKey}[#lt]
