[#-- @ftlvariable name="triggerReasonDescription" type="java.lang.String" --]
[#-- @ftlvariable name="baseUrl" type="java.lang.String" --]
[#-- @ftlvariable name="build" type="com.atlassian.bamboo.chains.Chain" --]
[#-- @ftlvariable name="buildSummary" type="com.atlassian.bamboo.chains.ChainResultsSummary" --]
[#-- @ftlvariable name="htmlUtils" type="com.atlassian.bamboo.util.HtmlUtils" --]
[#-- @ftlvariable name="executedJobs" type="int" --]

[#include "notificationCommons.ftl"]
[#include "notificationCommonsText.ftl" ]
-----------------------------------------------------------------------
[#if buildSummary.successful]
[@buildNotificationTitleText build buildSummary/] was successful[@showRestartCount buildSummary/].
[#else]
[@buildNotificationTitleText build buildSummary/] failed[@showRestartCount buildSummary/].
[/#if]
-----------------------------------------------------------------------
[#if triggerReasonDescription?has_content]
    ${triggerReasonDescription}[#lt]
[/#if]
[@showJobAndTestSummary buildSummary executedJobs/][#lt]

${baseUrl}/browse/${buildSummary.planResultKey}/

[#list ctx.getWebPanelsForResultsSummary("notification.completedbuild.text", buildSummary) as webpanel]
${webpanel}
[/#list]

[#if buildSummary.failed]
[#assign failingJobsSection]
[#assign failedResults = buildSummary.failedJobResults/]

--------------
Failing Jobs
--------------
[#assign failedJob = false/]
[#list buildSummary.stageResults as stageResult]
    [#list stageResult.sortedBuildResults as jobResult]
        [#if jobResult.failed]
            [#assign failedJob = true /]
            [@displayJob jobResult stageResult/]
        [/#if]
    [/#list]
[/#list]
[#if !failedJob]
No failed jobs found.
[/#if]

[/#assign]
[#if failedJob || !(buildSummary.mergeResult?? && buildSummary.mergeResult.hasFailed()) ]
${failingJobsSection}
[/#if]
[/#if]
[#if buildSummary.commits?has_content]

--------------
Code Changes
--------------
[#list buildSummary.commits as commit]
[#if commit_index gte 3][#break][/#if]
[#assign guessedRevision = commit.guessChangeSetId()!("")]
${commit.author.fullName}[#if guessedRevision?has_content] (${guessedRevision})[/#if]:

${htmlUtils.addPrefixToLines(">", commit.comment)}

[/#list]
[/#if]

[#assign testSummary = buildSummary.testResultsSummary /]
[#assign hasExistingFailedTests=testSummary.existingFailedTestCount gt 0 /]
[#assign hasNewlyFailingTests=testSummary.newFailedTestCaseCount gt 0 /]
[#assign hasFixedTests=testSummary.fixedTestCaseCount gt 0 /]
[#assign numTests=0 /]
[#assign maxTests=25 /]
[#if buildSummary.testResults?? && (hasExistingFailedTests || hasNewlyFailingTests || hasFixedTests)]
[#assign testResults = buildSummary.testResults /]

--------------
Tests
--------------
[#if hasNewlyFailingTests]
[@displayChainsTestList "New Test Failures" testSummary.newFailedTestCaseCount testResults.newFailedTests /]
[/#if]
[#if hasExistingFailedTests]
[@displayChainsTestList "Existing Test Failures" testSummary.existingFailedTestCount testResults.existingFailedTests /]
[/#if]
[#if hasFixedTests]
[@displayChainsTestList "Fixed Tests" testSummary.fixedTestCaseCount testResults.fixedTests /]
[/#if]
[/#if]

--
This message is automatically generated by Atlassian Bamboo