[#include "notificationCommonsText.ftl" ]
[@buildNotificationTitleText build buildSummary/] [#t]
[#if buildSummary.successful]
was SUCCESSFUL[#t]
[#if buildSummary.testResultsSummary.successfulTestCaseCount > 0]
 (with ${buildSummary.testResultsSummary.successfulTestCaseCount} tests)[#rt]
[/#if]
[#elseif buildSummary.failed]
has FAILED[#t]
[#if buildSummary.testResultsSummary.failedTestCaseCount > 0]
 (${buildSummary.testResultsSummary.failedTestCaseCount} tests failed[#rt]
[#if buildSummary.testResultsSummary.existingFailedTestCount > 0]
, [#t]
[#if buildSummary.testResultsSummary.newFailedTestCaseCount > 0]
${buildSummary.testResultsSummary.newFailedTestCaseCount} [#t]
[#else]
no [#t]
[/#if]
failures were new[#t]
[/#if]
)[#t]
[#elseif buildSummary.mergeResult?? && buildSummary.mergeResult.mergeState == "FAILED"]
 (merge failed)[#rt]
[#elseif  buildSummary.mergeResult?? && buildSummary.mergeResult.pushState == "FAILED"]
 (push failed)[#rt]
[/#if]
[#else]
was NOT BUILT[#t]
[/#if]
[#assign authors=buildSummary.uniqueAuthors /]
[#if authors?has_content]
  [#if authors.size() <= 3]
. Change made by [#t]
      [#assign first=true/]
      [#list authors as author]
            [#if !first]
                [#if author_has_next]
, [#t]
                [#else]
 and [#rt]
                [/#if]
            [#else]
                [#assign first=false]
            [/#if]
${author.fullName}[#t]
      [/#list]
.[#t]
   [#else]
. Change made by ${authors.size()} authors.[#t]
    [/#if]
[/#if]