[#-- @ftlvariable name="stageState" type="com.atlassian.bamboo.chains.StageExecution" --]
[#-- @ftlvariable name="chainExecution" type="com.atlassian.bamboo.chains.ChainExecution" --]
[#-- @ftlvariable name="chain" type="com.atlassian.bamboo.chains.Chain" --]

[#assign chainResultKey = chainExecution.planResultKey/]

-----------------------------------------------------------
[#if stageState.successful]
Stage ${stageState.name} of chain ${chainResultKey} was successful.
[#else]
Stage ${stageState.name} of chain ${chainResultKey} failed.
[/#if]
${baseUrl}/chain/result/viewChainResult.action?buildKey=${chain.key}&buildNumber=${chainResultKey.buildNumber}
-----------------------------------------------------------

[#list stageState.builds as build]
[#if build.successful ]
    Build ${build.planResultKey} successful.[#lt]
[#else]
    [#if build.completed ]
        Build ${build.planResultKey} failed.[#lt]
    [#else]
        Build ${build.planResultKey} not executed.[#lt]
    [/#if]
[/#if]
    ${baseUrl}/browse/${build.planResultKey}/[#lt]

[/#list]

--
This message is automatically generated by Atlassian Bamboo
