[#include "/${parameters.templateDir}/simple/dynamic-field-parameters.ftl" /]
<input type="checkbox" name="${parameters.name?html}" value="${parameters.fieldValue?html}"[#rt/]
[#if ContainUtil.contains(parameters.nameValue, "true") ||
     ContainUtil.contains(parameters.nameValue, true) ||
     ContainUtil.contains(parameters.checked, "true") ||
     ContainUtil.contains(parameters.checked, true)]
 checked="checked"[#rt/]
[/#if]
[#if parameters.disabled!false]
 disabled="disabled"[#rt/]
[/#if]
[#if parameters.readonly??]
 readonly="readonly"[#rt/]
[/#if]
[#if parameters.tabindex??]
 tabindex="${parameters.tabindex?html}"[#rt/]
[/#if]
[#if parameters.id??]
 id="${parameters.id?html}"[#rt/]
[/#if]
[#if parameters.cssClass??]
 class="${parameters.cssClass?html}"[#rt/]
[/#if]
[#if parameters.cssStyle??]
 style="${parameters.cssStyle?html}"[#rt/]
[/#if]
[#if parameters.title??]
 title="${parameters.title?html}"[#rt/]
[/#if]
[#include "/${parameters.templateDir}/simple/scripting-events.ftl" /]
/>
<input type="hidden" name="checkBoxFields" value="${parameters.name?html}" />[#rt/]