<pre[#rt/]
[#if (parameters.id)?has_content]
 id="${parameters.id?html}"[#rt/]
[/#if]
[#if parameters.cssClass?exists]
 class="${parameters.cssClass?html}"[#rt/]
[/#if]
[#if parameters.cssStyle?exists]
 style="${parameters.cssStyle?html}"[#rt/]
[/#if]
>[#rt/]
[#if parameters.nameValue?exists]
    [@ww.property value="parameters.nameValue" /][#t/]
[/#if]
</pre>
