[#if parameters.type?exists && parameters.type=="button"]
<button type="submit"[#rt/]
[#if parameters.name?exists]
 name="${parameters.name?html}"[#rt/]
[/#if]
[#if parameters.nameValue?exists]
 value="[@ww.property value="parameters.nameValue"/]"[#rt/]
[/#if]
[#if parameters.cssClass?exists]
 class="${parameters.cssClass?html}"[#rt/]
[/#if]
[#if parameters.cssStyle?exists]
 style="${parameters.cssStyle?html}"[#rt/]
[/#if]
[#include "/${parameters.templateDir}/simple/scripting-events.ftl"/]
>[#if parameters.label?exists][@ww.property value="parameters.label"/][#rt/][/#if]</button>
[#else]
[#if parameters.type?exists && parameters.type=="image"]
<input type="image"[#rt/]
[#if parameters.label?exists]
 alt="${parameters.label?html}"[#rt/]
[/#if]
[#if parameters.src?exists]
 src="${parameters.src?html}"[#rt/]
[/#if]
[#else]
<input type="submit"[#rt/]
[/#if]
[#if parameters.name?exists]
 name="${parameters.name?html}"[#rt/]
[/#if]
[#if parameters.nameValue?exists]
 value="[@ww.property value="parameters.nameValue"/]"[#rt/]
[/#if]
[#if parameters.disabled?exists && parameters.disabled?is_boolean && parameters.disabled]
  disabled="true"[#rt/]
[/#if]
[#if parameters.cssClass?exists]
 class="${parameters.cssClass?html}"[#rt/]
[/#if]
[#if parameters.cssStyle?exists]
 style="${parameters.cssStyle?html}"[#rt/]
[/#if]
[#if parameters.title?exists]
 title="${parameters.title?html}"[#rt/]
[#elseif parameters.titleKey?exists]
 title="[@ww.text name='${parameters.titleKey?html}' /]"[#rt/]
[/#if]
[#if parameters.id?exists]
 id="${parameters.id?html}"[#rt/]
[/#if]
[#include "/${parameters.templateDir}/simple/scripting-events.ftl" /]
[#if !(parameters.hideAccessKey!true) || parameters.customAccessKey??]
    [#if parameters.customAccessKey??]
 accesskey="${parameters.customAccessKey}"[#rt/]
    [#else]
 accesskey="${action.getText('global.key.submit')}"[#rt/]
    [/#if]
[/#if]
[#if parameters.tabindex?exists]
 tabindex="${parameters.tabindex?html}"[#rt/]
[/#if]
/>[#t/]
[/#if]
