[#-- @ftlvariable name="action" type="com.atlassian.bamboo.ww2.actions.labels.EditLabelsAction" --]
[#-- @ftlvariable name="" type="com.atlassian.bamboo.ww2.actions.labels.EditLabelsAction" --]
[#assign submitBtn]<input type="submit" value="[@ww.text name='global.buttons.add' /]" class="aui-button aui-button-primary" />[/#assign]
[@ww.form id='labelForm' action="addLabels" namespace="/build/label/ajax" cssClass="top-label"]
    [@ww.hidden name='buildKey' /]
    [#if buildNumber?has_content]
        [@ww.hidden name='buildNumber' /]
    [/#if]
    [@ww.textfield labelKey=(buildNumber?has_content?string('labels.edit.prompt', 'labels.plan.edit.prompt')) name='labelInput' after=submitBtn /]
[/@ww.form]
[#import "/fragments/labels/labels.ftl" as lb /]
[@lb.showLabelsWithNone immutablePlan resultsSummary false /]