[#-- @ftlvariable name="baseUrl" type="java.lang.String" --]
[#-- @ftlvariable name="buildSummary" type="com.atlassian.bamboo.chains.ChainResultsSummary" --]
[#-- @ftlvariable name="build" type="com.atlassian.bamboo.chains.Chain" --]
[#include "../notificationCommons.ftl"]
[#include "notificationCommonsHtmlIm.ftl" ]
[#assign authors = buildSummary.uniqueAuthors/]
[#if buildSummary.successful]
[@buildNotificationResultLink baseUrl build buildSummary/] passed[@showRestartCount buildSummary/]. [@testSummary buildSummary/]${buildSummary.reasonSummary}[#lt]
[#else]
[@buildNotificationResultLink baseUrl build buildSummary/] failed[@showRestartCount buildSummary/]. [@testSummary buildSummary/]${buildSummary.reasonSummary}[#lt]
[/#if]
