[#ftl]
[#-- @implicitly included --]
[#-- @ftlroot "" --]
[#-- @ftlroot "../webapp" --]
[#-- @ftlroot "." --]

[#-- @ftlvariable name="req" type="org.apache.struts2.dispatcher.StrutsRequestWrapper" --]
[#-- @ftlvariable name="decorator" type="com.opensymphony.module.sitemesh.mapper.DefaultDecorator" --]
[#-- @ftlvariable name="durationUtils" type="com.atlassian.bamboo.utils.DurationUtils" --]
[#-- @ftlvariable name="htmlUtils" type="com.atlassian.bamboo.util.HtmlUtils" --]
[#-- @ftlvariable name="ctx" type="com.atlassian.bamboo.ww2.FreemarkerContext" --]
[#-- @ftlvariable name="page" type="com.opensymphony.module.sitemesh.parser.FastPage"  --]
[#-- @ftlvariable name="UrlMode" type="com.atlassian.plugin.webresource.UrlMode"  --]
[#-- @ftlvariable name="PrettyLength" type="com.atlassian.bamboo.utils.PrettyLength"  --]
[#-- @ftlvariable name="webResourceManager" type="com.atlassian.plugin.webresource.WebResourceManager"  --]
[#-- @ftlvariable name="ContainUtil" type="org.apache.struts2.util.ContainUtil"  --]
[#-- @ftlvariable name="soy" type="com.atlassian.bamboo.ww2.BambooFreemarkerManagerSoyHelpers.SoyHelper"  --]
[#-- @ftlvariable name="featureManager" type="com.atlassian.bamboo.FeatureManager" --]
[#-- @ftlvariable name="webwork" type="org.apache.struts2.util.StrutsUtil"--]

[#-- Common param names. Note that if you add anything here, it will prevent IDEA from guessing the property type if the
that property is both listed here and present on the action--]
[#-- @ftlvariable name="brs" type="com.atlassian.bamboo.resultsummary.BuildResultsSummary" --]
[#-- @ftlvariable name="cb" type="com.atlassian.bamboo.v2.build.CurrentlyBuilding" --]
[#-- @ftlvariable name="i18n" type="com.atlassian.bamboo.utils.i18n.I18nBean" --]
[#-- @ftlvariable name="jiraIssueUtils" type="com.atlassian.bamboo.jira.jiraissues.JiraIssueUtils" --]
[#-- @ftlvariable name="staticResourcePrefix" type="java.lang.String" --]


[#import "/lib/components.ftl" as cp ]
[#import "/lib/dojo.ftl" as dj ]
[#import "freemarker-lib/ui.ftl" as ui ]
[#import "freemarker-lib/help.ftl" as help ]
[#import "freemarker-lib/functions.ftl" as fn ]
