[#-- @ftlvariable name="resultsSummary" type="com.atlassian.bamboo.resultsummary.ResultsSummary" --]
${resultsSummary.getBuildResultKey()} [#t]
[#if resultsSummary.buildState =="Successful"]
was SUCCESSFUL [#t]
[#if resultsSummary.testResultsSummary.successfulTestCaseCount > 0]
(with ${resultsSummary.testResultsSummary.successfulTestCaseCount} tests) [#t]
[/#if]
[#elseif resultsSummary.buildState == "Failed"]
has FAILED [#t]
[#if resultsSummary.testResultsSummary.failedTestCaseCount > 0]
(${resultsSummary.testResultsSummary.failedTestCaseCount} tests failed) [#t]
[/#if]
[#else]
was NOT BUILT [#t]
[/#if]
: [#t]
${triggerReason}[#t]
