[#assign cssClass = 'text short-field periodPicker' /]
[#include "/${parameters.templateDir}/${parameters.theme}/controlheader.ftl" /]
[#include "/${parameters.templateDir}/simple/text.ftl" /]
[@ww.select name=parameters.periodField value=parameters.periodValue list=['days', 'weeks', 'months'] theme='simple' cssClass="select" mediumField=true /]
[#include "/${parameters.templateDir}/${parameters.theme}/controlfooter.ftl" /]
