[#-- @ftlvariable name="tag" type="org.apache.struts2.components.Radio" --]
[#include "/${parameters.templateDir}/simple/dynamic-field-parameters.ftl" /]
<fieldset[#if (parameters.id)?has_content] id="fieldArea_${parameters.id}"[/#if] class="group[#if parameters.required!false] required[/#if]">

    [#if parameters.label?? || parameters.labelKey??]
        <legend[#if (parameters.id)?has_content] id="fieldLabelArea_${parameters.id}"[/#if]><span>[#rt/]
            [#if parameters.labelKey?has_content]
                [@ww.text name=parameters.labelKey /][#t/]
            [#elseif parameters.label?has_content]
                ${parameters.label}[#t/]
            [/#if]
            [#if parameters.required!false]
                <span class="aui-icon icon-required"></span><span class="content"> (required)</span>[#t/]
            [/#if]
        </span></legend>[#lt/]
    [/#if]

    [#if parameters.matrix!false]<div class="matrix[#if parameters.matrixCssClass??] ${parameters.matrixCssClass?html}[/#if]">[/#if]
    [#if parameters.list??]
        [@ww.iterator value="parameters.list"]
            [#if parameters.listKey??]
                [#assign itemKey = stack.findValue(parameters.listKey)/]
            [#else]
                [#assign itemKey = stack.findValue('top')/]
            [/#if]
            [#if parameters.listValue??]
                [#assign itemValue = stack.findString(parameters.listValue)/]
            [#else]
                [#assign itemValue = stack.findString('top')/]
            [/#if]
            <div class="radio">

                <input type="radio" name="${parameters.name?html}" id="${parameters.id?html}${itemKey?html}" [#rt/]
                    [#if parameters.nameValue??]
                        [#assign nameValue = parameters.nameValue/]
                        [#if parameters.nameValue?is_collection]
                            [#assign nameValue = parameters.nameValue[0]/]
                        [/#if]
                        [#if tag.contains(nameValue, itemKey)  || (nameValue?? && nameValue?string == itemKey)]checked="checked" [#t/][/#if]
                    [/#if]

                    [#if itemKey??]value="${itemKey?html}" [#t/][/#if]
                    [#if parameters.disabled!false]disabled="disabled" [#t/][/#if]
                    [#if parameters.tabindex??]tabindex="${parameters.tabindex?html}" [#t/][/#if]
                    class="radio[#if parameters.cssClass??] ${parameters.cssClass?html}[/#if]" [#t/]
                    [#if parameters.cssStyle??]style="${parameters.cssStyle?html}" [#t/][/#if]
                    [#if parameters.title??]title="${parameters.title?html}" [#t/][/#if]
                    [#include "/${parameters.templateDir}/simple/scripting-events.ftl" /]
                />[#lt/]
                <label for="${parameters.id?html}${itemKey?html}">[#rt/]
                    [#if parameters.i18nPrefixForValue?has_content]
                        [@ww.text name='${parameters.i18nPrefixForValue}.${itemValue}' /][#t]
                    [#else]
                        ${itemValue}[#t/]
                    [/#if]
                </label>[#lt/]
                [#if parameters.listDescription?? || parameters.showDescription??]
                    <div class="description">[#rt/]
                        [#if parameters.i18nPrefixForValue?has_content]
                            [@ww.text name='${parameters.i18nPrefixForValue}.${itemValue}.description' /][#t/]
                        [#else]
                            ${stack.findString(parameters.listDescription)!}[#t/]
                        [/#if]
                    </div>[#lt/]
                [/#if]
                [#if itemKey?? && tag.getParameters().containsKey('content.' + itemKey)]
                    [@ui.bambooSection dependsOn='${parameters.name?html}' showOn='${itemKey?html}' cssClass='field-group']
                        ${tag.getParameters().get('content.' + itemKey)}
                    [/@ui.bambooSection]
                [/#if]
            </div>
        [/@ww.iterator]
    [/#if]
    [#if parameters.matrix?? && parameters.matrix==true]
        [#include "/${parameters.templateDir}/${parameters.theme}/controlfooter-core.ftl" /]
        </div>
    [#else]
        [#assign fieldFooterInfo][#include "/${parameters.templateDir}/${parameters.theme}/controlfooter-core.ftl" /][/#assign]
        [#if fieldFooterInfo?trim?has_content]
            <div class="field-group">${fieldFooterInfo}</div>
        [/#if]
    [/#if]

</fieldset>
